#!/usr/bin/env python3
"""
Generate a synthetic school year with KNOWN, PLANTED signals, so the analytics
engine can be scored on whether it finds them -- and, just as importantly, on
whether it stays quiet where nothing was planted.

Planted ground truth:
  A. STU-A1  genuine individual gap on INTEGRATION (-0.30), normal elsewhere
  B. GROUP 1 systemic gap on SOURCES: the whole class sits near 0.42
  C. STU-A2  trajectory decline: fine until day 150, then -0.25 on everything
  D. STU-A3  clean student, nothing wrong -> must NOT be flagged (false-positive probe)
  E. EVERYONE improves +0.12 over the year -> Term 1 must NOT read as a deficit
  F. The December paper is genuinely harder (-0.20 on every item) -> must NOT
     read as a period effect once item difficulty is controlled
  G. GROUP 2 is a parallel class with NO sources problem -> must NOT inherit
     group 1's systemic flag
"""
import random, uuid, datetime as dt

random.seed(20260911)
def U(): return str(uuid.uuid4())

TENANT = U()
YEAR   = U()
SUBJ   = U(); DEPT = U()
TAXO   = U()
G1, G2 = U(), U()
TERMS  = [(U(), 'Term 1', 1, '2025-09-01', '2025-12-12'),
          (U(), 'Term 2', 2, '2025-12-13', '2026-03-27'),
          (U(), 'Term 3', 3, '2026-03-28', '2026-06-30')]
YEAR_START = dt.date(2025, 9, 1)

TOPICS = [('ALG','Algebra'), ('INT','Integration'), ('SRC','Sources'),
          ('STAT','Statistics'), ('GEO','Geometry'), ('PROB','Probability')]
TAGS = {code: U() for code, _ in TOPICS}

N_PER_GROUP = 24
students = []
for gi, g in enumerate([G1, G2]):
    for i in range(N_PER_GROUP):
        students.append({
            'id': U(), 'code': f'STU-{"AB"[gi]}{i+1}', 'group': g, 'gi': gi,
            'ability': max(0.30, min(0.92, random.gauss(0.66, 0.11))),
        })
S = {s['code']: s for s in students}

# 14 assessments spread across the year
assessments = []
for k in range(14):
    day = 12 + k * 19
    date = YEAR_START + dt.timedelta(days=day)
    term = next(t[0] for t in TERMS
                if dt.date.fromisoformat(t[3]) <= date <= dt.date.fromisoformat(t[4]))
    # The December paper: genuinely harder for everyone.
    hard = -0.20 if date.month == 12 else 0.0
    for g in (G1, G2):
        assessments.append({'id': U(), 'group': g, 'day': day, 'date': date,
                            'term': term, 'hard': hard, 'k': k})

def pct_for(stu, topic, a):
    p = stu['ability']
    p += 0.12 * (a['day'] / 270.0)          # E: universal growth
    p += a['hard']                          # F: harder December paper
    p += random.gauss(0, 0.065)             # noise
    if stu['code'] == 'STU-A1' and topic == 'INT': p -= 0.30      # A
    if stu['gi'] == 0 and topic == 'SRC':          p -= 0.26      # B (group 1 only -> G)
    if stu['code'] == 'STU-A2' and a['day'] > 150: p -= 0.25      # C
    return max(0.02, min(1.0, p))

out = []
w = out.append
w("-- GENERATED by db/test/generate_synthetic.py -- do not edit by hand")
w("BEGIN;")
w(f"INSERT INTO platform.tenant (id, slug, name, country_code) VALUES "
  f"('{TENANT}','synthetic-school','Synthetic Test School','GR');")
w(f"INSERT INTO org.academic_year (id, tenant_id, label, starts_on, ends_on, is_current) "
  f"VALUES ('{YEAR}','{TENANT}','2025-2026','2025-09-01','2026-06-30',true);")
for tid, label, seq, s0, s1 in TERMS:
    w(f"INSERT INTO org.term (id, tenant_id, academic_year_id, label, seq, starts_on, ends_on) "
      f"VALUES ('{tid}','{TENANT}','{YEAR}','{label}',{seq},'{s0}','{s1}');")
w(f"INSERT INTO org.department (id, tenant_id, name) VALUES ('{DEPT}','{TENANT}','Sciences');")
w(f"INSERT INTO org.subject (id, tenant_id, department_id, code, name) "
  f"VALUES ('{SUBJ}','{TENANT}','{DEPT}','MATH','Mathematics');")
w(f"INSERT INTO curric.taxonomy (id, owner_tenant_id, code, name, axis, subject_id) "
  f"VALUES ('{TAXO}','{TENANT}','MATH-TOPICS','Mathematics topics','topic','{SUBJ}');")
for code, label in TOPICS:
    w(f"INSERT INTO curric.tag (id, taxonomy_id, code, label, nominal_minutes) "
      f"VALUES ('{TAGS[code]}','{TAXO}','{code}','{label}',600);")
for g, lab in [(G1,'11M/1'), (G2,'11M/2')]:
    w(f"INSERT INTO org.teaching_group (id, tenant_id, academic_year_id, subject_id, label, year_level) "
      f"VALUES ('{g}','{TENANT}','{YEAR}','{SUBJ}','{lab}','Y11');")
for s in students:
    w(f"INSERT INTO org.person (id, tenant_id, external_ref, given_name, family_name, is_student) "
      f"VALUES ('{s['id']}','{TENANT}','{s['code']}','{s['code']}','Test',true);")
    w(f"INSERT INTO org.enrolment (tenant_id, student_id, teaching_group_id, from_date) "
      f"VALUES ('{TENANT}','{s['id']}','{s['group']}','2025-09-01');")

for a in assessments:
    w(f"INSERT INTO gradebook.assessment (id, tenant_id, teaching_group_id, term_id, title, kind, "
      f"occurred_on, max_total) VALUES ('{a['id']}','{TENANT}','{a['group']}','{a['term']}',"
      f"'Assessment {a['k']+1}','summative','{a['date']}',10);")
    a['items'] = []
    for j in range(8):
        topic = TOPICS[j % len(TOPICS)][0]
        iid = U()
        a['items'].append((iid, topic))
        w(f"INSERT INTO gradebook.item (id, tenant_id, assessment_id, seq, label, max_value, topic_tag_id) "
          f"VALUES ('{iid}','{TENANT}','{a['id']}',{j+1},'Q{j+1}',10,'{TAGS[topic]}');")

rows = []
for a in assessments:
    for s in students:
        if s['group'] != a['group']:
            continue
        for iid, topic in a['items']:
            p = pct_for(s, topic, a)
            rows.append(f"('{TENANT}','{iid}','{s['id']}',{round(p*10,3)},10,'scored','{a['date']}')")

w("INSERT INTO gradebook.result (tenant_id, item_id, student_id, raw_value, max_value, status, observed_on) VALUES")
for i in range(0, len(rows), 500):
    chunk = rows[i:i+500]
    w(",\n".join(chunk) + ("," if i + 500 < len(rows) else ";"))

# Teaching time: SOURCES was under-taught in group 1 -- a curriculum finding,
# not a teaching one. The engine should surface that context alongside the flag.
for g in (G1, G2):
    for code, _ in TOPICS:
        n_lessons = 4 if (g == G1 and code == 'SRC') else 14
        for li in range(n_lessons):
            w(f"INSERT INTO org.lesson (tenant_id, teaching_group_id, held_on, minutes, topic_tag_id) "
              f"VALUES ('{TENANT}','{g}','{YEAR_START + dt.timedelta(days=20+li*7)}',45,'{TAGS[code]}');")

w("COMMIT;")
w(f"-- TENANT_ID {TENANT}")
w(f"-- GROUP1 {G1}")
w(f"-- GROUP2 {G2}")
w(f"-- TAG_INT {TAGS['INT']}")
w(f"-- TAG_SRC {TAGS['SRC']}")

open('db/test/synthetic.sql','w').write("\n".join(out))
open('db/test/synthetic_ids.sql','w').write(f"""\\set tenant '{TENANT}'
\\set group1 '{G1}'
\\set group2 '{G2}'
\\set tag_int '{TAGS['INT']}'
\\set tag_src '{TAGS['SRC']}'
""")
print(f"students={len(students)} assessments={len(assessments)} results={len(rows)}")
